### ISSUE TITLE
What is proposed in this PR?

### ISSUE THREAD

**Issue by 0x6669736b696c** [ConsumerDataStandardsAustralia/standards#227] opened 2021-12-05 23:43 UTC
@CDR-API-Stream What changes do you suggest are being proposed here?

I would point out these are corrections to past changes that were essentially typos - not a change that is effectively changing anything at all.

Happy to propose a change using the formal process, if you can help me identify any actual changes being proposed here?

_Originally posted by @0x6669736b696c in https://github.com/ConsumerDataStandardsAustralia/standards/issues/224#issuecomment-985075893_

**Comment by CDR-API-Stream** [comment] 2021-12-09 22:22
This issue is a duplicate of thread #224.

@0x6669736b696c as stated previously, the standards can only be changed via a formal process that results in a decision of the Data Standards Chair and after review by a formal Advisory Committee.

For this change to progress through that process could you please raise this change as a change request in the [standards maintenance issue tracker](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/).

**Closed by CDR-API-Stream** 2021-12-09 22:22 UTC
