### ISSUE TITLE
NFR: Traffic Thresholds

### ISSUE THREAD

**Issue by ahlawatsb** [ConsumerDataStandardsAustralia/standards#101] opened 2020-02-24 22:39 UTC
Currently under the standard - non functional requirements for Traffic Threhold a 300 TPS across all channels (both customer present and unattended) has been prescribed.
https://consumerdatastandardsaustralia.github.io/standards/#traffic-thresholds
For a smaller Data Holder it would mean significant increase in Infra to handle this load and its quite onerous/not practical. Can you please provide additional guidance?

**Comment by mattp-rab** [comment] 2020-02-24 23:16
Hi @ahlawatsb, in case it helps our interpretation of this NFR is that there is an implicit "if needed" clause. That is, this NFR is only a requirement in the event of that level of traffic being experienced. Our understanding is that it won't be assessed as part of an accreditation process but as part of the mandatory reporting after the fact. In other words, there is no need to invest heavily in infra to satisfy this number if this number will never be reached. Each DH will be in a good position to estimate if and when this might be the case for their own implementation. I am aware that this is also contingent on the ADRs conforming to [their NFRs](https://consumerdatastandardsaustralia.github.io/standards/#data-recipient-requirements).

I would be very interested to see if our interpretation is in alignment or not with formal advice given on this thread.

**Comment by perlboy** [comment] 2020-02-24 23:31
I believe @mattp-rab is correct, the TPS was intended as an upper bound. If Holder's are complying with the response time thresholds specified in the NFR's they would have met the requirements with the TPS peak being a cap of required delivery.

**Comment by CDR-API-Stream** [comment] 2020-02-24 23:39
Hi @ahlawatsb, it is preferred if queries of this nature are raised on the [standards maintenance repo](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues).  This repo is primarily used for formal consultation on significant standards changes and communication of decisions.

That said, the comments from @mattp-rab and @perlboy are accurate.  The intent of the thresholds is not to require holders to demonstrate that they can support that level of traffic, it is to give an upper bound above which holders can reject traffic.

For traffic levels below the threshold there is an expectation that requests will be successfully responded to so infrastructure should be planned to accommodate that outcome based on the size of the ADI's customer base.

**Closed** 2020-02-28 03:22 UTC
Labels: InfoSec Decision Proposal, Proposal Pending
